### PR TITLE
Add pull request reviews support

### LINKED ISSUE #252: PR Review Information not showing in JIRA
I recently migrated my team to a managed JIRA instance and added this plugin.  While it appears that it is linking branches and PRs, it does not seem to be linking PR Review information (reviewer & state of review) in the Development Information panel.

### PR DESCRIPTION
**Pull request by Raul6469**
This pull request adds pull requests reviews in the Development view ✨ 

image

This is related to #382 and should fix #252

### CODE REVIEW

**Review by techgaun — APPROVED** [review]
nice, we need this in :)

**Comment by jtaekema** [comment]
Excited to see this feature but haven't seen any recent updates, @techgaun or @Raul6469 any news?

**Review by maximechbt — APPROVED** [review]

**Comment by gcphost** [comment]
Subbed, would love for this to work.

**Comment by thombergs** [comment]
Hey @Raul6469, I can't promise a date, but we'll be looking at this soon. :)

**Comment by atrigueiro** [comment]
Closing this PR in favour of https://github.com/integrations/jira/pull/447

**Pull request closed without merging**
