### PR TITLE
Update README.md to be clear about GHES support

### PR DESCRIPTION
**Pull request by andrekolodochka**
This README may create a confusion for customers. GitHub Enterprise can refer to either GitHub Enterprise Server or GitHub Enterprise Cloud. This integration supports GitHub Enterprise Cloud, but not GitHub Enterprise Server.

I've added clarification about what might be considered in the future, i.e. either GitHub Server or ghithub.com with Jira Server/Data Center

### CODE REVIEW

**Review by mboudreau — APPROVED** [review]
Thanks for the clarification! Much needed :)

**Comment by mboudreau** [comment]
Hm, build seems stuck. I'll have to look into this.

**Comment by andrekolodochka** [comment]
btw, the [docs on Atlassian side](https://support.atlassian.com/jira-cloud-administration/docs/integrate-with-github/) also need to be updated. Wherever it says `GitHub Enterprise` on that page, it really should be `GitHub Enterprise Server`. Not sure who's the best person to ping about that.

**Comment by mboudreau** [comment]
@andrekolodochka Yep, we'll change those docs once this is merged.  I just updated this branch to see if build will actually run.

**Comment by mboudreau** [comment]
Hm, status is still stuck.  Trying to close PR and reopen it as it's been reported that this fixes it.

**Comment by mboudreau** [comment]
@andrekolodochka When you say Github Enterprise Server, do you mean Github AE?  Github Enterprise is still github.com.

**Comment by andrekolodochka** [comment]
Not GitHub AE. GitHub Enterprise can mean GitHub Enterprise Cloud (on githib.com) or GitHub Enterprise Server (on-prem solution).

**Comment by mboudreau** [comment]
Right.  Man this is confusing...

**Comment by mboudreau** [comment]
Weird, build is still stuck.  Need to investigate further, but since this is a README change, not exactly risky to merge in.

**Comment by andrekolodochka** [comment]
> Right. Man this is confusing...

I think it's because in the past GitHub had `GitHub Enterprise` (on-prem solution) and `GitHub Business Cloud` (on github.com). Later those became `GitHub Enterprise Server` and `GitHub Enterprise Cloud` but the docs did not reflect that change.

**Pull request merged**
