### PR TITLE
[ARC-35] security vulnerability in markdown

### PR DESCRIPTION
**Pull request by rachellerathbone**
Resolved markdown vulnerability by removing markdown.js library and adding a block of code to handle pulling issue keys from reference text.

Screen Shot 2021-03-29 at 5 00 54 pm

### CODE REVIEW

**Comment by saquibkhan** [comment]
Have you tested the basic functionality with this fix?

**Comment by saquibkhan** [comment]
Can you check if the right email is setup on your local git config, as I don't see proper identity on the commits

image

**Comment by rachellerathbone** [comment]
> Have you tested the basic functionality with this fix?

Yep, tested the functionality out on master and made sure I saw the same behaviour on this branch with the new logic. Only diff is that the master keys are in lowercase (converted via the markdown library)

Screen Shot 2021-04-11 at 8 34 24 pm

Screen Shot 2021-04-11 at 8 22 51 pm

**Comment by rachellerathbone** [comment]
> Can you check if the right email is setup on your local git config, as I don't see proper identity on the commits
> 
> image

Guess you're looking for my email attached to this account and not my atlassian email (which is what was in my gitconfig). I just updated it. Do I need to make another commit now so you can confirm?

**Comment by saquibkhan** [comment]
Yes, its better to update the commit, I see now  in other PR for new commits its fine
image

**Comment by rachellerathbone** [comment]
> Yes, its better to update the commit, I see now in other PR for new commits its fine

I just merged my other PR and then merged master into this one. Anything else I need to do to get this approved?

**Review by saquibkhan — APPROVED** [review]

**Comment by saquibkhan** [comment]
@rachellerathbone Please note that after merging into master, deployment is manually triggered by us. First, it's deployed on stage, we do the basic tests and then push to prod.

**Pull request merged**
