### PR TITLE
Send merge commit flag

### PR DESCRIPTION
**Pull request by felipe-gdr**
Adds the `MERGE_COMMIT` flag for merge commits on the DevInfo bulk push operation.

fixes: #345

### CODE REVIEW

**Comment by felipe-gdr** [comment]
I haven't writen tests for this change and I really appreciate some help on that area :-) 

My changes are 100% based on documentation about probot and GitHub Api.

Those are the assumptions I've made:
- `github.repos.getCommit` returns a promise wrapping an object of type [GitGetCommitResponse](https://probot.github.io/api/latest/interfaces/githubapi.html#gitgetcommitresponse)
- the list of parents obtained by the `parents` properties returns an array of the commit's parents
- a commit with 2 parents is a merge commit

**Comment by rachellerathbone** [comment]
Hey @felipe-gdr. Just started looking into your PR. Will update you shortly.

**Comment by rachellerathbone** [comment]
Hey @felipe-gdr. Thanks for this PR. I've made some additions to your work (but from your branch so you'll still get the cred) and opened a [new PR.](https://github.com/integrations/jira/pull/456). Going to close this one out. My team will merge mine in over the next few days and you should see your changes in prod next week.

**Comment by felipe-gdr** [comment]
Thanks @rachellerathbone !

**Pull request closed without merging**
